/**
 * SEED SCRIPT — Run once to populate all 18 packages into MongoDB
 * Usage: node seed.js
 * Place this file in your backend root folder
 */

require('dotenv').config();
const mongoose = require('mongoose');
const ExplorePackage = require('../models/ExplorePackage');

const MONGO_URI = process.env.MONGO_URI || process.env.MONGODB_URI || 'mongodb://localhost:27017/dgtlmart';

const packagesToSeed = [
  // ── Website Development ────────────────────────────────────────────────────
  {
    Name: 'Basic Website',
    category: 'Website Development',
    price: 15000,
    description: 'Perfect for startups and small businesses needing a simple online presence.',
    buttonText: 'Get Started',
    status: 'Active',
    features: [
      'Website Type: Static Website',
      'Pages: Up to 5 Pages',
      'Custom Design: No',
      'Responsive: Yes',
      'CMS: No',
      'SEO: Yes',
      'Ecommerce: No',
      'Payment Gateway: No',
      'Blog: No',
      'Contact Form: Yes',
      'Social Media: No',
      'SSL: Yes',
      'Speed Optimization: Basic',
      'Technical Support: Limited',
      'Maintenance: 1 Month',
      'Delivery Time: 15 days',
    ],
  },
  {
    Name: 'Business Website',
    category: 'Website Development',
    price: 35000,
    description: 'Ideal for growing businesses that need a dynamic, professional website.',
    buttonText: 'Get Started',
    status: 'Active',
    features: [
      'Website Type: Dynamic Website',
      'Pages: Up to 25 Pages',
      'Custom Design: Yes',
      'Responsive: Yes',
      'CMS: WordPress / WIX',
      'SEO: Yes',
      'Ecommerce: No',
      'Payment Gateway: No',
      'Blog: Yes',
      'Contact Form: Yes',
      'Social Media: Yes',
      'SSL: Yes',
      'Speed Optimization: Advanced',
      'Custom Features: Limited',
      'Technical Support: Standard',
      'Maintenance: 3 Months',
      'Delivery Time: 1 Month',
    ],
  },
  {
    Name: 'E-Commerce Website',
    category: 'Website Development',
    price: 75000,
    description: 'Complete e-commerce solution with unlimited products and payment gateway.',
    buttonText: 'Get Started',
    status: 'Active',
    features: [
      'Website Type: E-Commerce',
      'Pages: Unlimited',
      'Custom Design: Yes',
      'Responsive: Yes',
      'CMS: Shopify / WooCommerce / Custom',
      'SEO: Yes',
      'Ecommerce: Yes',
      'Payment Gateway: Yes',
      'Blog: Yes',
      'Contact Form: Yes',
      'Social Media: Yes',
      'SSL: Yes',
      'Speed Optimization: Advanced',
      'Custom Features: Yes',
      'Technical Support: Full',
      'Maintenance: 6 Months',
      'Products: 50',
      'Delivery Time: 2 Months',
    ],
  },

  // ── SEO ───────────────────────────────────────────────────────────────────
  {
    Name: 'Standard SEO',
    category: 'SEO',
    price: 18000,
    description: 'Entry-level SEO plan for businesses starting their organic growth journey.',
    buttonText: 'Get Started',
    status: 'Active',
    features: [
      'Website Audit: Basic Audit',
      'Keyword Research: Up to 10 Keywords',
      'On Page: Yes',
      'Meta Tags: Yes',
      'Header Tags: Yes',
      'Image Optimization: No',
      'Internal Linking: Limited',
      'Technical SEO: Basic',
      'Backlinks: 50',
      'Blog Writing: 2 Blogs',
      'Local SEO: No',
      'Monthly Reports: Yes',
      'Google Analytics: Basic',
      'Competitor Analysis: No',
    ],
  },
  {
    Name: 'Premium SEO',
    category: 'SEO',
    price: 30000,
    description: 'Advanced SEO plan with local SEO, backlinks, and detailed reporting.',
    buttonText: 'Get Started',
    status: 'Active',
    features: [
      'Website Audit: Advanced Audit',
      'Keyword Research: Up to 30 Keywords',
      'On Page: Yes',
      'Meta Tags: Yes',
      'Image Optimization: Yes',
      'Internal Linking: Yes',
      'Technical SEO: Advanced',
      'Backlinks: 200',
      'Blog Writing: 4 Blogs',
      'Local SEO: Yes',
      'Google My Business: Yes',
      'Monthly Reports: Detailed',
      'Competitor Analysis: Yes',
      'Schema Markup: Yes',
    ],
  },
  {
    Name: 'E-Commerce SEO',
    category: 'SEO',
    price: 45000,
    description: 'Full-scale SEO for e-commerce stores with product and category optimization.',
    buttonText: 'Get Started',
    status: 'Active',
    features: [
      'Website Audit: Advanced Audit',
      'Keyword Research: Up to 50 Keywords',
      'On Page: Yes',
      'Image Optimization: Yes',
      'Technical SEO: Advanced',
      'Backlinks: 400',
      'Blog Writing: 6 Blogs',
      'Local SEO: Yes',
      'Google My Business: Yes',
      'Monthly Reports: Detailed',
      'Competitor Analysis: Yes',
      'Ecommerce Product Optimization: Yes',
      'Category Page Optimization: Yes',
      'Schema Markup: Yes',
      'Product Reviews: Yes',
    ],
  },

  // ── Social Media ──────────────────────────────────────────────────────────
  {
    Name: 'Basic SMM',
    category: 'Social Media',
    price: 18000,
    description: 'Basic social media management for Facebook and Instagram.',
    buttonText: 'Get Started',
    status: 'Active',
    features: [
      'Platforms: Facebook, Instagram',
      'Posts Per Month: 10',
      'Custom Graphics: Yes',
      'Video Content: No',
      'Hashtag Research: Basic',
      'Ad Campaign Management: No',
      'Community Engagement: Limited',
      'Influencer Collaboration: No',
      'Performance Reports: Monthly',
      'Content Strategy: Basic',
      'Competitor Analysis: No',
      'Dedicated Account Manager: No',
    ],
  },
  {
    Name: 'Standard SMM',
    category: 'Social Media',
    price: 40000,
    description: 'Multi-platform social media management with video content and ad campaigns.',
    buttonText: 'Get Started',
    status: 'Active',
    features: [
      'Platforms: Facebook, Instagram, LinkedIn',
      'Posts Per Month: 16',
      'Custom Graphics: Yes',
      'Video Content: Yes',
      'Hashtag Research: Advanced',
      'Ad Campaign Management: Yes (Basic)',
      'Community Engagement: Moderate',
      'Performance Reports: Bi-Weekly',
      'Content Strategy: Detailed',
      'Competitor Analysis: Yes',
      'Dedicated Account Manager: Yes',
      'Story & Reel Creation: Yes',
    ],
  },
  {
    Name: 'Premium SMM',
    category: 'Social Media',
    price: 85000,
    description: 'Full-scale social media management across all 5 major platforms.',
    buttonText: 'Get Started',
    status: 'Active',
    features: [
      'Platforms: All Major 5 Platforms',
      'Posts Per Month: 30',
      'Custom Graphics: Yes',
      'Video Content: Yes',
      'Hashtag Research: Expert',
      'Ad Campaign Management: Yes (Advanced)',
      'Community Engagement: High',
      'Influencer Collaboration: Yes',
      'Performance Reports: Weekly',
      'Content Strategy: Comprehensive',
      'Dedicated Account Manager: Yes',
      'Story & Reel Creation: Yes',
      'Response Management: Yes',
    ],
  },

  // ── Digital Marketing ─────────────────────────────────────────────────────
  {
    Name: 'Basic Package',
    category: 'Digital Marketing',
    price: 30000,
    description: 'Entry-level digital marketing with SEO, Google Ads, and social media.',
    buttonText: 'Get Started',
    status: 'Active',
    features: [
      'SEO Optimization: Basic On-Page & Off-Page',
      'Google Ads: Search & Display',
      'Meta Ads: Brand Awareness & Traffic',
      'LinkedIn Ads: No',
      'Landing Pages: 1 Landing Page',
      'Lead Magnet: No',
      'CRM Integration: No',
      'Email Marketing: Limited',
      'Blog Writing: 2 Blogs',
      'Social Media Management: Basic (12 Posts)',
      'Retargeting Campaigns: No',
      'Performance Reports: Monthly',
      'Budget Recommendation: 10K - 25K',
      'Dedicated Account Manager: No',
    ],
  },
  {
    Name: 'Standard Package',
    category: 'Digital Marketing',
    price: 75000,
    description: 'Advanced digital marketing with full funnel strategy and automation.',
    buttonText: 'Get Started',
    status: 'Active',
    features: [
      'SEO Optimization: Advanced SEO',
      'Google Ads: Search, Display & Remarketing',
      'Meta Ads: Traffic & Conversions',
      'LinkedIn Ads: Yes',
      'Landing Pages: 2 Landing Pages',
      'Lead Magnet: Yes',
      'CRM Integration: Zoho',
      'Email Marketing: Yes',
      'Blog Writing: 4 Blogs',
      'Social Media Management: Moderate (20 Posts)',
      'Retargeting Campaigns: Yes',
      'Marketing Automation: Yes',
      'Performance Reports: Bi-Weekly',
      'Budget Recommendation: 25K - 1L',
      'Dedicated Account Manager: Yes',
    ],
  },
  {
    Name: 'Premium Package',
    category: 'Digital Marketing',
    price: 180000,
    description: 'Comprehensive digital marketing with full automation and influencer marketing.',
    buttonText: 'Get Started',
    status: 'Active',
    features: [
      'SEO Optimization: Full SEO (On-Page, Off-Page, Technical)',
      'Google Ads: Search, Display, Shopping, YouTube',
      'Meta Ads: Full-Funnel Strategy',
      'LinkedIn Ads: Yes (B2B Targeting)',
      'Landing Pages: 10 Landing Pages',
      'Lead Magnet: Yes (E-Books, Webinars)',
      'CRM Integration: Zoho',
      'Email Marketing: Yes (Automated)',
      'Blog Writing: 8 Blogs',
      'Social Media Management: Full (30+ Posts)',
      'Retargeting Campaigns: Yes (Multi-Channel)',
      'Influencer Marketing: Yes',
      'Affiliate Marketing: Yes (ROI-Based)',
      'Performance Reports: Weekly',
      'Budget Recommendation: 1L to 5L',
      'Dedicated Account Manager: Yes',
    ],
  },

  // ── Google Ads ────────────────────────────────────────────────────────────
  {
    Name: 'Basic Google Ads',
    category: 'Google Ads',
    price: 20000,
    description: 'Basic Google Ads management with Search & Display campaigns.',
    buttonText: 'Get Started',
    status: 'Active',
    features: [
      'Campaign Type: Search & Display',
      'Ad Copies: Yes',
      'Keyword Research: Basic',
      'Bid Management: Manual',
      'Landing Page Optimization: No',
      'A/B Testing: No',
      'Conversion Tracking: Yes',
      'Ad Extensions: Limited',
      'Geo Targeting: Basic',
      'Remarketing: No',
      'YouTube Ads: No',
      'Shopping Ads: No',
      'Performance Reports: Monthly',
      'Dedicated Account Manager: No',
      'Budget Recommendation: 10K - 25K',
    ],
  },
  {
    Name: 'Standard Google Ads',
    category: 'Google Ads',
    price: 40000,
    description: 'Advanced Google Ads with remarketing, YouTube ads, and A/B testing.',
    buttonText: 'Get Started',
    status: 'Active',
    features: [
      'Campaign Type: Search, Display & Remarketing',
      'Ad Copies: Yes',
      'Keyword Research: Advanced',
      'Bid Management: Automated + Manual',
      'Landing Page Optimization: Yes',
      'A/B Testing: Yes',
      'Conversion Tracking: Yes',
      'Ad Extensions: Moderate',
      'Geo Targeting: Advanced',
      'Remarketing: Yes',
      'YouTube Ads: Yes',
      'Shopping Ads: No',
      'Performance Reports: Bi-Weekly',
      'Dedicated Account Manager: Yes',
      'Budget Recommendation: 25K - 1L',
    ],
  },
  {
    Name: 'Premium Google Ads',
    category: 'Google Ads',
    price: 75000,
    description: 'Full Google Ads suite with Shopping, YouTube, and expert bid management.',
    buttonText: 'Get Started',
    status: 'Active',
    features: [
      'Campaign Type: Search, Display, YouTube, Shopping & Remarketing',
      'Ad Copies: Yes',
      'Keyword Research: Expert',
      'Bid Management: Automated + Manual',
      'Landing Page Optimization: Yes',
      'A/B Testing: Yes',
      'Conversion Tracking: Yes',
      'Ad Extensions: Comprehensive',
      'Geo Targeting: Expert',
      'Remarketing: Yes',
      'YouTube Ads: Yes',
      'Shopping Ads: Yes',
      'Performance Reports: Weekly',
      'Dedicated Account Manager: Yes',
      'Budget Recommendation: 1L+',
    ],
  },

  // ── Meta Ads ──────────────────────────────────────────────────────────────
  {
    Name: 'Basic Meta Ads',
    category: 'Meta Ads',
    price: 15000,
    description: 'Basic Meta Ads for brand awareness and traffic generation.',
    buttonText: 'Get Started',
    status: 'Active',
    features: [
      'Campaign Type: Brand Awareness & Traffic',
      'Ad Copywriting: Yes',
      'Creative Design: Standard',
      'Audience Targeting: Basic',
      'Pixel Setup: No',
      'A/B Testing: No',
      'Retargeting: No',
      'Lookalike Audiences: No',
      'Lead Generation Ads: No',
      'Ecommerce Dynamic Ads: No',
      'Performance Reports: Monthly',
      'Account Manager: No',
      'Budget Recommendation: 10K - 25K',
    ],
  },
  {
    Name: 'Standard Meta Ads',
    category: 'Meta Ads',
    price: 30000,
    description: 'Advanced Meta Ads with retargeting, pixel setup, and carousel ads.',
    buttonText: 'Get Started',
    status: 'Active',
    features: [
      'Campaign Type: Traffic, Engagement & Conversions',
      'Ad Copywriting: Yes',
      'Creative Design: Advanced',
      'Audience Targeting: Detailed',
      'Pixel Setup: Yes',
      'A/B Testing: Yes',
      'Retargeting: Yes',
      'Lookalike Audiences: Yes',
      'Lead Generation Ads: Yes',
      'Carousel & Video Ads: Yes',
      'Ecommerce Dynamic Ads: No',
      'Performance Reports: Bi-Weekly',
      'Account Manager: Yes',
      'Budget Recommendation: 25K - 1L',
    ],
  },
  {
    Name: 'Premium Meta Ads',
    category: 'Meta Ads',
    price: 70000,
    description: 'Full-funnel Meta Ads strategy with dynamic e-commerce ads and expert targeting.',
    buttonText: 'Get Started',
    status: 'Active',
    features: [
      'Campaign Type: Full-Funnel Strategy',
      'Ad Copywriting: Yes',
      'Creative Design: Expert',
      'Audience Targeting: Highly Refined',
      'Pixel Setup: Yes',
      'A/B Testing: Yes',
      'Retargeting: Yes',
      'Lookalike Audiences: Yes',
      'Lead Generation Ads: Yes',
      'Carousel & Video Ads: Yes',
      'Ecommerce Dynamic Ads: Yes',
      'Stories Ads: Yes',
      'Performance Reports: Weekly',
      'Account Manager: Yes',
      'Budget Recommendation: 1L+',
    ],
  },
];

async function seedPackages() {
  try {
    console.log('🔌 Connecting to MongoDB...');
    await mongoose.connect(MONGO_URI);
    console.log('✅ Connected to MongoDB');

    // Check if already seeded
    const existing = await ExplorePackage.countDocuments();
    if (existing > 0) {
      console.log(`⚠️  Database already has ${existing} packages.`);
      console.log('   Do you want to re-seed? Delete existing packages first:');
      console.log('   Run: await ExplorePackage.deleteMany({}) in mongo shell');
      console.log('   OR change the if-condition below to force re-seed.');
      await mongoose.disconnect();
      return;
    }

    console.log(`📦 Seeding ${packagesToSeed.length} packages...`);
    const result = await ExplorePackage.insertMany(packagesToSeed);
    console.log(`✅ Successfully seeded ${result.length} packages!`);

    // Summary
    const categories = [...new Set(packagesToSeed.map(p => p.category))];
    categories.forEach(cat => {
      const count = packagesToSeed.filter(p => p.category === cat).length;
      console.log(`   ${cat}: ${count} packages`);
    });

  } catch (err) {
    console.error('❌ Seed error:', err.message);
  } finally {
    await mongoose.disconnect();
    console.log('🔌 Disconnected from MongoDB');
  }
}

seedPackages();