export default function OfferLetter() {
  return (
    <div className="max-w-4xl mx-auto text-center mt-10">
      <h1 className="text-3xl font-bold text-slate-800 mb-4">Your Offer Letter</h1>
      <div className="bg-white p-10 rounded-2xl shadow border border-slate-200">
        <svg className="w-20 h-20 text-blue-300 mx-auto mb-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
        </svg>
        <h2 className="text-xl font-semibold text-slate-700 mb-2">Coming Soon</h2>
        <p className="text-slate-500">Your offer letter is currently being generated by the administration team. It will be available here to view and download once approved.</p>
      </div>
    </div>
  );
}
